// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package neo.grpc.proto;

public final class StudentProto {
  private StudentProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_neo_grpc_proto_MyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_neo_grpc_proto_MyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_neo_grpc_proto_MyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_neo_grpc_proto_MyResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_neo_grpc_proto_StudentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_neo_grpc_proto_StudentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_neo_grpc_proto_StudentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_neo_grpc_proto_StudentResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_neo_grpc_proto_StudentResponseList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_neo_grpc_proto_StudentResponseList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_neo_grpc_proto_StreamRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_neo_grpc_proto_StreamRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_neo_grpc_proto_StreamResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_neo_grpc_proto_StreamResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rStudent.proto\022\016neo.grpc.proto\"\035\n\tMyReq" +
      "uest\022\020\n\010username\030\001 \001(\t\"\036\n\nMyResponse\022\020\n\010" +
      "realname\030\002 \001(\t\"\035\n\016StudentRequest\022\013\n\003age\030" +
      "\001 \001(\005\":\n\017StudentResponse\022\014\n\004name\030\001 \001(\t\022\013" +
      "\n\003age\030\002 \001(\005\022\014\n\004city\030\003 \001(\t\"O\n\023StudentResp" +
      "onseList\0228\n\017studentResponse\030\001 \003(\0132\037.neo." +
      "grpc.proto.StudentResponse\"%\n\rStreamRequ" +
      "est\022\024\n\014request_info\030\001 \001(\t\"\'\n\016StreamRespo" +
      "nse\022\025\n\rresponse_info\030\001 \001(\t2\356\002\n\016StudentSe" +
      "rvice\022P\n\025GetRealNameByUsername\022\031.neo.grp" +
      "c.proto.MyRequest\032\032.neo.grpc.proto.MyRes" +
      "ponse\"\000\022W\n\020GetStudentsByAge\022\036.neo.grpc.p" +
      "roto.StudentRequest\032\037.neo.grpc.proto.Stu" +
      "dentResponse\"\0000\001\022b\n\027GetStudentsWrapperBy" +
      "Age\022\036.neo.grpc.proto.StudentRequest\032#.ne" +
      "o.grpc.proto.StudentResponseList\"\000(\001\022M\n\006" +
      "BiTalk\022\035.neo.grpc.proto.StreamRequest\032\036." +
      "neo.grpc.proto.StreamResponse\"\000(\0010\001B \n\016n" +
      "eo.grpc.protoB\014StudentProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_neo_grpc_proto_MyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_neo_grpc_proto_MyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_neo_grpc_proto_MyRequest_descriptor,
        new String[] { "Username", });
    internal_static_neo_grpc_proto_MyResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_neo_grpc_proto_MyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_neo_grpc_proto_MyResponse_descriptor,
        new String[] { "Realname", });
    internal_static_neo_grpc_proto_StudentRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_neo_grpc_proto_StudentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_neo_grpc_proto_StudentRequest_descriptor,
        new String[] { "Age", });
    internal_static_neo_grpc_proto_StudentResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_neo_grpc_proto_StudentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_neo_grpc_proto_StudentResponse_descriptor,
        new String[] { "Name", "Age", "City", });
    internal_static_neo_grpc_proto_StudentResponseList_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_neo_grpc_proto_StudentResponseList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_neo_grpc_proto_StudentResponseList_descriptor,
        new String[] { "StudentResponse", });
    internal_static_neo_grpc_proto_StreamRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_neo_grpc_proto_StreamRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_neo_grpc_proto_StreamRequest_descriptor,
        new String[] { "RequestInfo", });
    internal_static_neo_grpc_proto_StreamResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_neo_grpc_proto_StreamResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_neo_grpc_proto_StreamResponse_descriptor,
        new String[] { "ResponseInfo", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
